name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  run_tests:
    uses: taa-epam/ai-dial-ci/.github/workflows/python_docker_pr.yml@a4b69fd204c6e2ace25aa10c3c30e1adad78587b
    secrets:
      GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
      GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
    with:
      platforms: "linux/amd64,linux/arm64"