name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  run_tests:
    uses: taa-epam/ai-dial-ci/.github/workflows/python_docker_pr.yml@d3d1b6a535c9264f7dcc6c3d671c181e156ea245
    secrets:
      GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
      GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
    with:
      platforms: "linux/amd64,linux/arm64"