name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  run_tests:
    uses: taa-epam/ai-dial-ci/.github/workflows/python_docker_pr.yml@5e27c0b18fb57e87c7b1e51a2571e425fdc93f13
    secrets:
      GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
      GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
    with:
      platforms: "linux/amd64,linux/arm64"